language: go
go:
  - 1.2
  - 1.3
  - tip
install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/robertkrimen/otto
  - go get gopkg.in/fsnotify.v0
script:
  - go test -cover github.com/slvmnd/soy/...
